export converted_modulus_T1_Gl, T1_Gl_module, tjurina_Gl_number, T1_Gl_basis, has_only_rigid_singularities,T1_GL_sheaf, has_only_determinantal_rigid_singularities

#TODO temporary export, remove it later


export global_auxiliar_PHN_index, local_PHN_multiplicity, components, global_PHN_index,local_PHN_index,global_polar_multiplicities,global_euler_obstruction

#TODO temporary export, remove it later

function _S_2(A::MatElem)
  n_rows = number_of_rows(A)
  return [_R_ij(A, i, j) for i in 1:n_rows for j in 1:n_rows]
end



function _S_3(A::MatElem)
  n_cols = number_of_columns(A)
  return [_C_ij(A, i, j) for i in 1:n_cols for j in 1:n_cols]
end

function _J(A::MatElem{<:MPolyRingElem})
  return [derivative.(A, i) for i in 1:ngens(parent(A[1, 1]))]
end

function _modulus_T1_Gl(M::MatElem{<:MPolyRingElem})
  return vcat(_J(M), _S_2(M), _S_3(M))
end

function converted_modulus_T1_Gl(M::MatElem{<:MPolyRingElem})
  L = base_ring(parent(M))
  F = free_module(L, number_of_rows(M) * number_of_columns(M))
  # transpose is important for rowwise linear index of vev
  mod_T1_Gl = _modulus_T1_Gl(transpose(M))
  S, _ = sub(F, F.(vec.(Array.(mod_T1_Gl))))
  return S
end

function T1_Gl_module(M::MatElem{<:MPolyRingElem}, reorder=false)
  S = converted_modulus_T1_Gl(M)
  F = ambient_free_module(S)
  if reorder
    k = ngens(F)
    F_gens = gens(F)
    reordered_gens = vcat(
      [F_gens[k - 1]], [F_gens[j] for j in 2:(k - 2)], [F_gens[1], F_gens[k]]
    )
    sigma = hom(F, F, reordered_gens)
    S_gens = ambient_representatives_generators(S)
    S_gens_reordered = sigma.(S_gens)
    S, _ = sub(F, S_gens_reordered)
  end
  LS = leading_module(S, invlex(F) * negdeglex(base_ring(F)))
  T1_Gl, _ = quo(F, LS)
  return T1_Gl
end

function tjurina_Gl_number(M::MatElem{<:MPolyRingElem}, reorder=false)
  tau = vector_space_dim(T1_Gl_module(M, reorder))
  return tau == -1 ? PosInf() : tau
end

function T1_Gl_basis(M::MatElem{<:MPolyRingElem}, reorder=false)
  return vector_space_basis(T1_Gl_module(M, reorder))
end
#  ord = invlex(ambient_free_module(S))*negdeglex(base_ring(S))

# matrix(transpose(reshape([S[i] for i in 1:6], 3,2)))



function T1_Gl_sheaf(M::MatElem{<:MPolyRingElem})
  S = converted_modulus_T1_Gl(M)
  F = ambient_free_module(S)
  return quo(F, S)[1]
end

T1_GL_sheaf(X::DeterminantalGerm) = pre_saturated_module(T1_GL_module(X))

has_only_determinantally_rigid_singularities(X::DeterminantalGerm) = is_zero(T1_GL_sheaf(X))

function has_only_rigid_singularities(M::MatElem{<:MPolyRingElem})
  return vector_space_dim(T1_Gl_sheaf(M)) == 0
end


@doc raw"""

Let `(Xtil,p)` be given by the  `Spec U^{-1}(R /I)`, where `R` is a polynomial
ring, `I` an ideal of it and `U` the complement of the maximal ideal corresponding
to `p`. Let J_total be the jacobian matrix augmented by the coeficientes of the differential 
of the function f and J be the ideal generated by the codim(X)+1 - minors of J_total. 

_PHN_locus(X::DeterminantalGerm, f::MPolyRingElem) returns the vector space R/J. 

global_auxiliar_PHN_index(X::DeterminantalGerm, f::MPolyRingElem) returns the dimension of the vector space R/I.

function local_PHN_multiplicity(X::DeterminantalGerm{<:BRT, <:RT, <:AST}, f::MPolyRingElem, p::Vector) 
  returns the dimension of the vector space given by the localization of the _PHN_locus(X, f) at the maximal
  ideal corresponding to `p`. 

function global_PHN_index(X::DeterminantalGerm{<:BRT, <:RT, <:AST}, f::MPolyRingElem, p::Vector) returns the number 
of zeros of the 1-form df lying on the regular part of X, that is,  
global_auxiliar_PHN_index(X::DeterminantalGerm, f::MPolyRingElem)-#{singular points of X}* local_PHN_multiplicity(X::DeterminantalGerm{<:BRT, <:RT, <:AST}, f::MPolyRingElem, p::Vector).

function local_PHN_index(X::DeterminantalGerm, f::MPolyRingElem, epsilon::Real = 1e-4) returns the 
  number of zeros of the 1-form df lying on the regular part of X close to the origin, for a given epsilon - 
  the choice of a "sufficiently small" epsilon depends on the essential smoothing (which is supposed to be generic enough).

# Example
```jldoctest
julia> R, (x1, x2, x3, x4, x5, x6) = polynomial_ring(QQ, ["x1", "x2", "x3", "x4", "x5", "x6"]);

julia> origin = complement_of_point_ideal(R, [0,0,0,0,0,0]);

julia> R_local, _ = localization(R, origin);

julia> t = 2;

julia> val_1=QQ(-1//4000000); val_2=QQ(-1//10); val_3=QQ(-1//10000000);

julia> M_vars = matrix(R, 2, 3, [x1, x2, x3, x4, x5, x1^4+x1*x2^2+x6^2]);

julia> M_pert = matrix(R, 2, 3, [ R(0), R(0), R(0),  R(0),  R(0), val_1]);

julia> M = M_vars + M_pert;

julia> M_local = change_base_ring(R_local, M);

julia> point_P = [QQ(0), QQ(0), QQ(0), QQ(0), QQ(0), 1//2000];

julia> Xtil = DeterminantalGerm(M, 2, point_P)
Spectrum
  of localization
    of quotient
      of multivariate polynomial ring in 6 variables x1, x2, x3, x4, ..., x6
        over rational field
      by ideal with 3 generators
    at complement of maximal ideal of point (0, 0, 0, 0, 0, 1//2000)

julia> Xtilrep=representative(Xtil);

julia> Xtilrep_sing,_=singular_locus(Xtilrep);

julia> vector_space_dim(OO(singular_locus(Xtilrep)[1]))
2

julia> f = 2*x1+5*x2 + 3*x3 - 5*x4 - 7*x5 + 11*x6;

julia> global_auxiliar_PHN_index(Xtil,f)
30

julia> local_PHN_multiplicity(Xtil,f,point_P)
7

julia> global_PHN_index(Xtil,f,point_P)
16

julia> local_PHN_index(Xtil,f,0.001)
7
```
"""



function _PHN_locus(X::DeterminantalGerm, f::MPolyRingElem)
  OO_repr = underlying_quotient(OO(X))
  R = base_ring(OO_repr)
  @assert R === parent(f)
  n, m, t = determinantal_type(X) 
  I_X = modulus(OO_repr)
  J_total = jacobian_matrix(vcat(gens(I_X), f))
  polys_crit = minors(J_total, codim(X) + 1)
  I = I_X + ideal(R, polys_crit)
  return quo(R, I)[1]
end


 function global_auxiliar_PHN_index(X::DeterminantalGerm, f::MPolyRingElem)
   return vector_space_dim(_PHN_locus(X, f))
 end

function local_PHN_multiplicity(
     X::DeterminantalGerm{<:BRT, <:RT, <:AST}, f::MPolyRingElem, p::Vector
  ) where {BRT<:Field, RT, AST}
   Q = _PHN_locus(X, f)
   LQ_p, _ = localization(Q, complement_of_point_ideal(base_ring(Q), p))
   return vector_space_dim(LQ_p)
 end

 function global_PHN_index(
    X::DeterminantalGerm{<:BRT, <:RT, <:AST}, 
    f::MPolyRingElem, 
    p::Vector
) where {BRT<:Field, RT, AST}

    idx_global = global_auxiliar_PHN_index(X, f)
    
    # Extração do representante e do lugar singular nativo
    Xrep = representative(X)
    Xrep_sing, _ = singular_locus(Xrep)
    dim_sing = vector_space_dim(OO(Xrep_sing))
    
    idx_local = local_PHN_multiplicity(X, f, p)
    
    return idx_global - (dim_sing * idx_local)
end


function _PHN_primary_decomposition(X::DeterminantalGerm, f::MPolyRingElem)
    return primary_decomposition(modulus(_PHN_locus(X, f)))
end

"""
    components(X::DeterminantalGerm, f::MPolyRingElem)

Prints information about the primary components of the PHN locus.
This function is intended for side effects (printing) and does not return a value.
"""
function components(X::DeterminantalGerm, f::MPolyRingElem)
    pd = _PHN_primary_decomposition(X, f)
    for (i, (q, p)) in enumerate(pd)
        println("\n--- Component $i with multiplicity $(degree(q)) ---")
        
         #'p' is the prime ideal where the point is 
         #'q' is the primary ideal giving the multiplicity of that point 
        println("Coordinates:")
        for gerador in gens(p)
           println("  ", gerador, " = 0")
        end
    end
end



function local_PHN_index(X::DeterminantalGerm, f::MPolyRingElem, epsilon::Real = 1e-4)
    # Recebe as coordenadas complexas (AcbFieldElem)
    raizes = _PHN_critical_roots(X, f)
    
    indice_local = 0
    
    for raiz in raizes
        # 1. Extrai o módulo geométrico da raiz (transforma o complexo em real)
        distancia_real = abs(raiz)
        
        # 2. Agora a conversão para Float64 funciona perfeitamente
        if Float64(distancia_real) < epsilon
            indice_local += 1
        end
    end
    
    return indice_local
end

@doc raw"""

_PHN_critical_roots(X::DeterminantalGerm, f::MPolyRingElem) returns the coordinates of the zeros of the 1-form df on the regular part of X.


julia> all_roots =Oscar. _PHN_critical_roots(Xtil, f)

julia> show(stdout, "text/plain", all_roots)
16-element Vector{AcbFieldElem}:
 [-1.838439 +/- 3.42e-7]
 [-0.00016514787 +/- 6.10e-12]
 [9.26158e-5 +/- 7.42e-11]
 [9.51928e-5 +/- 6.69e-11]
 [-4.856028e-5 +/- 4.27e-12] + [-8.139445e-5 +/- 8.16e-12]*im
 [-4.856028e-5 +/- 4.27e-12] + [8.139445e-5 +/- 8.16e-12]*im
 [-3.320500e-5 +/- 5.66e-12] + [-0.00011516586 +/- 8.41e-12]*im
 [-3.320500e-5 +/- 5.66e-12] + [0.00011516586 +/- 8.41e-12]*im
 [0.005464557 +/- 7.26e-10] + [-0.005383487 +/- 6.64e-10]*im
 [0.005464557 +/- 7.26e-10] + [0.005383487 +/- 6.64e-10]*im
 [0.03982093 +/- 6.10e-9] + [-0.20155859 +/- 5.91e-9]*im
 [0.03982093 +/- 6.10e-9] + [0.20155859 +/- 5.91e-9]*im
 [-2.471698 +/- 6.15e-7] + [-0.765792 +/- 7.02e-7]*im
 [-2.471698 +/- 6.15e-7] + [0.765792 +/- 7.02e-7]*im
 [0.4885593 +/- 3.37e-8] + [-1.0215439 +/- 5.74e-8]*im
 [0.4885593 +/- 3.37e-8] + [1.0215439 +/- 5.74e-8]*im

```
"""

function _PHN_critical_roots(X::DeterminantalGerm, f::MPolyRingElem)
    pd = _PHN_primary_decomposition(X, f)
    
    C = AcbField(512)
    all_roots = elem_type(C)[] 
    
    R = parent(f)
    n = nvars(R)
    R_uni, T = polynomial_ring(QQ, :T, cached=false)
    
    # Construção do ideal singular
    anel_base = base_ring(underlying_quotient(OO(X)))
    I_X = modulus(underlying_quotient(OO(X)))
    J_X = jacobian_matrix(gens(I_X))
    I_sing = I_X + ideal(anel_base, minors(J_X, codim(X)))
    
    for (q, p) in pd
        # Filtro Algébrico: Destrói a componente se ela for a singularidade
        I_teste = saturation(p, I_sing)
        anel_comp = quo(R, I_teste)[1]
        
        if vector_space_dim(anel_comp) == 0
            continue
        end
        
        # Lógica de extração de coordenadas originais preservada
        geradores = gens(p)
        poly_mult = geradores[1]
        
        vetor_subst = fill(R_uni(0), n)
        vetor_subst[n] = T
        
        poly_uni = evaluate(poly_mult, vetor_subst)
        poly_C = change_base_ring(C, poly_uni)
        
        append!(all_roots, roots(poly_C))
    end
    
    return all_roots
end


function global_polar_multiplicities(M::MatrixElem, t::Int, f::MPolyRingElem, point_P::Vector; print_list::Bool=true)
    R = parent(f)
    base_R = base_ring(R)
    current_vars = gens(R)
    
    current_M = M
    current_f = f
    current_p = point_P
    current_R = R
    
    # 1. CRIAR O VETOR PARA ARMAZENAR OS DADOS
    alphas = Int[] 
    
    #println("k = 0 (Original Variety):")
    X_0 = DeterminantalGerm(current_M, t, current_p)
    idx_0 = global_PHN_index(X_0, current_f, current_p)
    
    # 2. GUARDAR O ALPHA_0
    push!(alphas, idx_0) 
    #println("  -> Polar multiplicity: ", idx_0)
    
    d = dim(underlying_quotient(OO(X_0)))
    
    for k in 1:(d-1)
       # println("\nCalculating for k = $k...")
        
        coeffs = [rand(-20:20) for _ in 1:length(current_vars)]
        while all(x -> x == 0, coeffs)
            coeffs = [rand(-20:20) for _ in 1:length(current_vars)]
        end
        
        H = sum(c * v for (c, v) in zip(coeffs, current_vars))
        centered_H = H - evaluate(H, current_p)
        
        idx_to_eliminate = findfirst(x -> x != 0, coeffs)
        var_to_eliminate = current_vars[idx_to_eliminate]
        c_i = base_R(coeffs[idx_to_eliminate])
        
        new_names = [string(v) for v in current_vars if v != var_to_eliminate]
        new_R, new_vars = polynomial_ring(base_R, new_names)
        
        remainder = centered_H - c_i * var_to_eliminate
        
        remainder_subst = elem_type(new_R)[]
        for v in current_vars
            if v == var_to_eliminate
                push!(remainder_subst, new_R(0))
            else
                new_idx = findfirst(x -> string(x) == string(v), new_vars)
                push!(remainder_subst, new_vars[new_idx])
            end
        end
        
        remainder_expr_new_R = evaluate(remainder, remainder_subst)
        isolated_rule = -remainder_expr_new_R * inv(c_i)
        
        hom_images = elem_type(new_R)[]
        for v in current_vars
            if v == var_to_eliminate
                push!(hom_images, isolated_rule)
            else
                new_idx = findfirst(x -> string(x) == string(v), new_vars)
                push!(hom_images, new_vars[new_idx])
            end
        end
        
        reduction_map = hom(current_R, new_R, hom_images)
        
        current_M = map_entries(x -> reduction_map(x), current_M)
        current_f = reduction_map(current_f)
        current_p = deleteat!(copy(current_p), idx_to_eliminate)
        
        current_R = new_R
        current_vars = new_vars
        
        X_k = DeterminantalGerm(current_M, t, current_p)
        glob_idx = global_PHN_index(X_k, current_f, current_p)
        
        # 3. GUARDAR OS ALPHAS SUBSEQUENTES (k = 1, 2, ...)
        push!(alphas, glob_idx)
        
    end
  if print_list
        println("Sequence of Polar Multiplicities: ", alphas)
    end
    return alphas
end

function global_euler_obstruction(alphas::Vector{Int})
    eu_obstruction = 0
    for i in 1:length(alphas)
        eu_obstruction += (-1)^(i - 1) * alphas[i]
    end
    return eu_obstruction
end

function global_euler_obstruction(M::MatrixElem, t::Int, f::MPolyRingElem, point_P::Vector)
    # 1. Extrai a lista chamando a sua função arrumada
    alphas = global_polar_multiplicities(M, t, f, point_P;print_list=false)
    
    # 2. Envia a lista automaticamente para o Motor Matemático acima
    eu_obstruction = global_euler_obstruction(alphas)    
    
    return eu_obstruction
    
end