export T1_GL_basis, has_only_determinantally_rigid_singularities

#TODO temporary export, remove it later


export global_auxiliar_PHN_index, local_PHN_multiplicity, components, global_PHN_index,local_PHN_index, global_polar_multiplicities, global_euler_obstruction
#, calculate_complete_roots, calcular_distancias_origem




function T1_GL_basis(M::MatElem{<:MPolyRingElem}; mat_type::Symbol = :generic)
  return vector_space_basis(T1_GL_module(M, mat_type=mat_type))
end


T1_GL_sheaf(X::DeterminantalGerm) = pre_saturated_module(T1_GL_module(X))

has_only_determinantally_rigid_singularities(X::DeterminantalGerm) = is_zero(T1_GL_sheaf(X))

function has_only_determinantally_rigid_singularities(M::MatElem{<:MPolyRingElem}; mat_type::Symbol = :generic)
  return vector_space_dim(T1_GL_module(M, mat_type=mat_type)) == 0
end



@doc raw"""
Let `(Xtil,p)` be given by the `Spec U^{-1}(R/I)`, where `R` is a polynomial
ring, `I` an ideal of it and `U` the complement of the maximal ideal corresponding
to `p`. 
Let `J_total` be the jacobian matrix augmented by the coeficientes of the differential 
of the function `f` and `J` be the ideal generated by the (codim(X)+1)-minors of `J_total`. 

    _PHN_locus(X::DeterminantalGerm, f::MPolyRingElem) 

Return the vector space R/J. 

    global_auxiliar_PHN_index(X::DeterminantalGerm, f::MPolyRingElem) 

Return the dimension of the vector space R/I.

# Example
```jldoctest
julia> R, (x1, x2, x3, x4, x5, x6) = polynomial_ring(QQ, [:x1, :x2, :x3, :x4, :x5, :x6]);

julia> origin = complement_of_point_ideal(R, [0,0,0,0,0,0]);

julia> R_local, _ = localization(R, origin);

julia> t = 2;

julia> val_1 = QQ(-1//4000000); val_2 = QQ(-1//10); val_3 = QQ(-1//10000000);

julia> M_vars = matrix(R, 2, 3, [x1, x2, x3, x4, x5, x1^4 + x1*x2^2 + x6^2]);

julia> M_pert = matrix(R, 2, 3, [ R(0), R(0), R(0),  R(0),  R(0), val_1]);

julia> M = M_vars + M_pert;


julia> point_P = [QQ(0), QQ(0), QQ(0), QQ(0), QQ(0), 1//2000];

julia> Xtil = DeterminantalGerm(M, 2, point_P);

julia> Xtilrep = representative(Xtil);

julia> Xtilrep_sing, _ = singular_locus(Xtilrep);

julia> f = 2*x1 + 5*x2 + 3*x3 - 5*x4 - 7*x5 + 11*x6;

julia> global_auxiliar_PHN_index(Xtil, f)
30

```
"""
function _PHN_locus(X::DeterminantalGerm, f::MPolyRingElem)
  OO_repr = underlying_quotient(OO(X))
  R = base_ring(OO_repr)
  @req R === parent(f) "polynomial 'f' is not an element of the ambient_coordinate_ring of 'X'"
  n, m, t = determinantal_type(X) 
  I_X = modulus(OO_repr)
  J_total = jacobian_matrix(vcat(gens(I_X), f))
  polys_crit = minors(J_total, codim(X) + 1)
  I = I_X + ideal(R, polys_crit)
  return quo(R, I)[1]
end


 function global_auxiliar_PHN_index(X::DeterminantalGerm, f::MPolyRingElem)
   return vector_space_dim(_PHN_locus(X, f))
 end

@doc raw"""
    function local_PHN_multiplicity(X::DeterminantalGerm, f::MPolyRingElem, p::Vector) 
Return the dimension of the vector space given by the localization of the _PHN_locus(X, f) at the point `p`. 

# Example
```jldoctest
julia> R, (x1, x2, x3, x4, x5, x6) = polynomial_ring(QQ, [:x1, :x2, :x3, :x4, :x5, :x6]);

julia> origin = complement_of_point_ideal(R, [0,0,0,0,0,0]);

julia> R_local, _ = localization(R, origin);

julia> t = 2;

julia>  val_1 = QQ(-1//4000000); 

julia> M_vars = matrix(R, 2, 3, [x1, x2, x3, x4, x5, x1^4 + x1*x2^2 + x6^2]);

julia> M_pert = matrix(R, 2, 3, [ R(0), R(0), R(0),  R(0),  R(0), val_1]);

julia> M = M_vars + M_pert;


julia> point_P = [QQ(0), QQ(0), QQ(0), QQ(0), QQ(0), 1//2000];

julia> Xtil = DeterminantalGerm(M, 2, point_P);

julia> f = 2*x1 + 5*x2 + 3*x3 - 5*x4 - 7*x5 + 11*x6;

julia> local_PHN_multiplicity(Xtil,f,point_P)
```
"""
function local_PHN_multiplicity(
     X::DeterminantalGerm{<:BRT, <:RT, <:AST}, f::MPolyRingElem, p::Vector
  ) where {BRT<:Field, RT, AST}
   Q = _PHN_locus(X, f)
   LQ_p, _ = localization(Q, complement_of_point_ideal(base_ring(Q), p))
   return vector_space_dim(LQ_p)
 end

 @doc raw"""
    function global_PHN_index(X::DeterminantalGerm{<:BRT, <:RT, <:AST}, f::MPolyRingElem, p::Vector)

Return the number of zeros of the 1-form `df` lying on the regular part of `X`, that is,  
global_auxiliar_PHN_index(X, f) - #{singular points of X}*local_PHN_multiplicity(X, f, p).



# Example
```jldoctest
julia> R, (x1, x2, x3, x4, x5, x6) = polynomial_ring(QQ, [:x1, :x2, :x3, :x4, :x5, :x6]);

julia> origin = complement_of_point_ideal(R, [0,0,0,0,0,0]);

julia> R_local, _ = localization(R, origin);

julia> t = 2;

julia>  val_1 = QQ(-1//4000000); 

julia> M_vars = matrix(R, 2, 3, [x1, x2, x3, x4, x5, x1^4 + x1*x2^2 + x6^2]);

julia> M_pert = matrix(R, 2, 3, [ R(0), R(0), R(0),  R(0),  R(0), val_1]);

julia> M = M_vars + M_pert;

julia> point_P = [QQ(0), QQ(0), QQ(0), QQ(0), QQ(0), 1//2000];

julia> Xtil = DeterminantalGerm(M, 2, point_P);

julia> f = 2*x1 + 5*x2 + 3*x3 - 5*x4 - 7*x5 + 11*x6;

julia> global_PHN_index(Xtil,f,point_P)
16
```
"""
 function global_PHN_index(
    X::DeterminantalGerm{<:BRT, <:RT, <:AST}, 
    f::MPolyRingElem, 
    p::Vector
) where {BRT<:Field, RT, AST}

    idx_global = global_auxiliar_PHN_index(X, f)
    
    # Extração do representante e do lugar singular nativo
    Xrep = representative(X)
    Xrep_sing, _ = singular_locus(Xrep)
    dim_sing = vector_space_dim(OO(Xrep_sing))
    
    idx_local = local_PHN_multiplicity(X, f, p)
    
    return idx_global - (dim_sing * idx_local)
end


@doc raw"""
    components(X::DeterminantalGerm, f::MPolyRingElem)

Prints information about the primary components of the PHN locus.
This function is intended for side effects (printing) and does not return a value.
"""
function components(X::DeterminantalGerm, f::MPolyRingElem)
    pd = primary_decomposition(modulus(_PHN_locus(X, f)))
    for (i, (q, p)) in enumerate(pd)
        println("\n--- Component $i with multiplicity $(degree(q)) ---")
        
         #'p' is the prime ideal where the point is 
         #'q' is the primary ideal giving the multiplicity of that point 
        println("Coordinates:")
        for gerador in gens(p)
           println("  ", gerador, " = 0")
        end
    end
end


@doc raw"""
    _PHN_critical_roots(X::DeterminantalGerm, f::MPolyRingElem)

Return the coordinates of the zeros of the 1-form `df` on the regular part of `X` and its distances from the origin.

# Example
```jldoctest
julia> R, (x1, x2, x3, x4, x5, x6) = polynomial_ring(QQ, [:x1, :x2, :x3, :x4, :x5, :x6]);

julia> origin = complement_of_point_ideal(R, [0,0,0,0,0,0]);

julia> R_local, _ = localization(R, origin);

julia> t = 2;

julia>  val_1 = QQ(-1//40000000000);

julia> M_vars = matrix(R, 2, 3, [x1, x2, x3, x4, x5, x1^2 + x2^2 + x6^2]);

julia> M_pert = matrix(R, 2, 3, [ R(0), R(0), R(0),  R(0),  R(0), val_1]);

julia> M = M_vars + M_pert;

julia> point_P = [QQ(0), QQ(0), QQ(0), QQ(0), QQ(0), 1//200000];

julia> Xtil = DeterminantalGerm(M, 2, point_P);

julia> f = 2*x1 + 5*x2 + 3*x3 - 5*x4 - 7*x5 + 11*x6;

julia> Oscar._PHN_critical_roots(Xtil,f)
- Root 1 | Norm: [5.0000073e-6 +/- 6.92e-14]
- Root 2 | Norm: [4.9999927e-6 +/- 7.16e-14]
- Root 3 | Norm: [1.6778901 +/- 4.77e-8]
- Root 4 | Norm: [1.6778901 +/- 4.77e-8]
(Vector{AcbFieldElem}[[[-8.1649778e-7 +/- 4.30e-15], [-2.0412445e-6 +/- 5.71e-14], 0, 0, 0, [-4.4907378e-6 +/- 2.55e-14]], 
[[8.1649538e-7 +/- 4.28e-15], [2.0412385e-6 +/- 5.71e-14], 0, 0, 0, [4.4907246e-6 +/- 2.57e-14]], 
[[-0.13513514 +/- 6.10e-9] + [-0.23835597 +/- 5.11e-9]*im, [-0.33783784 +/- 5.25e-9] + [-0.59588993 +/- 7.78e-9]*im, 0, 0, 0, [-0.7432432 +/- 4.98e-8] + [-1.3109579 +/- 5.02e-8]*im], 
[[-0.13513514 +/- 6.10e-9] + [0.23835597 +/- 5.11e-9]*im, [-0.33783784 +/- 5.25e-9] + [0.59588993 +/- 7.78e-9]*im, 0, 0, 0, [-0.7432432 +/- 4.98e-8] + [1.3109579 +/- 5.02e-8]*im]], 
ArbFieldElem[[5.0000073e-6 +/- 6.92e-14], [4.9999927e-6 +/- 7.16e-14], [1.6778901 +/- 4.77e-8], [1.6778901 +/- 4.77e-8]])
```
"""
function _PHN_critical_roots(X, f; verbose=true)
    pd = primary_decomposition(modulus(Oscar._PHN_locus(X, f)))
    
    C = AcbField(512)
    all_roots = Vector{elem_type(C)}[] 
    all_norms = [] 
    
    root_index = 1 
    
    R = parent(f)
    n = nvars(R)
    R_uni, T = polynomial_ring(QQ, :T, cached=false)
    
    R_lex, vars_lex = polynomial_ring(QQ, [string(v) for v in gens(R)], internal_ordering=:lex)
    phi_to_lex = hom(R, R_lex, vars_lex)
    
    base_ring_X = base_ring(underlying_quotient(OO(X)))
    I_X = modulus(underlying_quotient(OO(X)))
    J_X = jacobian_matrix(gens(I_X))
    I_sing = I_X + ideal(base_ring_X, minors(J_X, codim(X)))
    
    # Só imprime o cabeçalho se verbose for verdadeiro
    if verbose 
        println("\n=== Critical Locus Report ===") 
    end
    
    for (q, p) in pd
        I_test = saturation(p, I_sing)
        comp_ring = quo(R, I_test)[1]
        
        if vector_space_dim(comp_ring) == 0
            continue
        end
        
        p_lex = ideal(R_lex, [phi_to_lex(g) for g in gens(p)])
        
        I_elim = eliminate(p_lex, vars_lex[1:n-1])
        poly_mult = gens(I_elim)[1]
        
        subst_vector = fill(R_uni(0), n)
        subst_vector[n] = T
        
        poly_uni = evaluate(poly_mult, subst_vector)
        poly_C = change_base_ring(C, poly_uni)
        
        roots_xn = roots(poly_C)
        
        parametrizations_C = typeof(poly_C)[]
        for i in 1:(n-1)
            h_i = normal_form(vars_lex[i], p_lex)
            h_i_uni = evaluate(h_i, subst_vector)
            push!(parametrizations_C, change_base_ring(C, h_i_uni))
        end
        
        for root_n in roots_xn
            point = elem_type(C)[]
            
            for i in 1:(n-1)
                coord_i = evaluate(parametrizations_C[i], root_n)
                push!(point, coord_i)
            end
            
            push!(point, root_n)
            
            distance = sqrt(sum(abs(c)^2 for c in point))
            
            # Só imprime a raiz se verbose for verdadeiro
            if verbose 
                println("- Root $root_index | Distance: ", distance) 
            end
            
            push!(all_roots, point)
            push!(all_norms, distance)
            
            root_index += 1 
        end
    end
    
    if verbose 
        println("=============================\n") 
    end
    
    return all_roots, all_norms
end

@doc raw"""
    function local_PHN_index(X::DeterminantalGerm, f::MPolyRingElem, epsilon::Real = 1e-4) 
Return the  number of zeros of the 1-form `df` lying on the regular part of `X` close to the origin, for a given `epsilon`sz\ - 
  the choice of a "sufficiently small" `epsilon` depends on the essential smoothing (which is supposed to be generic enough).




# Example
```jldoctest
julia> R, (x1, x2, x3, x4, x5, x6) = polynomial_ring(QQ, [:x1, :x2, :x3, :x4, :x5, :x6]);

julia> origin = complement_of_point_ideal(R, [0,0,0,0,0,0]);

julia> R_local, _ = localization(R, origin);

julia> t = 2;

julia>  val_1 = QQ(-1//4000000); 

julia> M_vars = matrix(R, 2, 3, [x1, x2, x3, x4, x5, x1^4 + x1*x2^2 + x6^2]);

julia> M_pert = matrix(R, 2, 3, [ R(0), R(0), R(0),  R(0),  R(0), val_1]);

julia> M = M_vars + M_pert;

julia> point_P = [QQ(0), QQ(0), QQ(0), QQ(0), QQ(0), 1//2000];

julia> Xtil = DeterminantalGerm(M, 2, point_P);

julia> f = 2*x1 + 5*x2 + 3*x3 - 5*x4 - 7*x5 + 11*x6;

julia> local_PHN_index(Xtil,f,0.001)
7
```
"""
function local_PHN_index(X::DeterminantalGerm, f::MPolyRingElem, epsilon::Real = 1e-4)
  
    roots, norms = _PHN_critical_roots(X, f; verbose=false)
    
    local_index = 0
    
    
    for distance in norms
        if Float64(distance) < epsilon
            local_index += 1
        end
    end
    
    return local_index
end

@doc raw"""
    function global_polar_multiplicities(M::MatrixElem, t::Int, f::MPolyRingElem, point_P::Vector; print_list::Bool=true) 
Return a list of the global polar multiplicities of a determinantal singularity. 
The list is ordered as follows: [alpha_0, alpha_1, alpha_2, ...], where alpha_0 is the global PHN index of the original variety 
and alpha_k is the global PHN index of the variety obtained by intersecting the original variety with a generic hyperplane k times.



# Example
```jldoctest
julia> R, (x1, x2, x3, x4, x5, x6) = polynomial_ring(QQ, [:x1, :x2, :x3, :x4, :x5, :x6]);

julia> origin = complement_of_point_ideal(R, [0,0,0,0,0,0]);

julia> R_local, _ = localization(R, origin);

julia> t = 2;

julia>  val_1 = QQ(-1//4000000);

julia> M_vars = matrix(R, 2, 3, [x1, x2, x3, x4, x5, x1^2 + x2^2 + x6^2]);

julia> M_pert = matrix(R, 2, 3, [ R(0), R(0), R(0),  R(0),  R(0), val_1]);

julia> M = M_vars + M_pert;

julia> point_P = [QQ(0), QQ(0), QQ(0), QQ(0), QQ(0), 1//2000];

julia> f = 2*x1 + 5*x2 + 3*x3 - 5*x4 - 7*x5 + 11*x6;

julia> global_polar_multiplicities(M,2,f,point_P)
Sequence of Polar Multiplicities: [4, 10, 13, 8]
```
"""
function global_polar_multiplicities(M::MatrixElem, t::Int, f::MPolyRingElem, point_P::Vector; print_list::Bool=true)
    R = parent(f)
    base_R = base_ring(R)
    current_vars = gens(R)
    
    current_M = M
    current_f = f
    current_p = point_P
    current_R = R
    
    # 1. CRIAR O VETOR PARA ARMAZENAR OS DADOS
    alphas = Int[] 
    
    #println("k = 0 (Original Variety):")
    X_0 = DeterminantalGerm(current_M, t, current_p)
    idx_0 = global_PHN_index(X_0, current_f, current_p)
    
    # 2. GUARDAR O ALPHA_0
    push!(alphas, idx_0) 
    #println("  -> Polar multiplicity: ", idx_0)
    
    d = dim(underlying_quotient(OO(X_0)))
    
    for k in 1:(d-1)
       # println("\nCalculating for k = $k...")
        
        coeffs = [rand(-20:20) for _ in 1:length(current_vars)]
        while all(is_zero, coeffs)
            coeffs = [rand(-20:20) for _ in 1:length(current_vars)]
        end
        
        H = sum(c * v for (c, v) in zip(coeffs, current_vars))
        centered_H = H - evaluate(H, current_p)
        
        idx_to_eliminate = findfirst(!is_zero, coeffs)
        var_to_eliminate = current_vars[idx_to_eliminate]
        c_i = base_R(coeffs[idx_to_eliminate])
        
        new_names = [string(v) for v in current_vars if v != var_to_eliminate]
        new_R, new_vars = polynomial_ring(base_R, new_names)
        
        remainder = centered_H - c_i * var_to_eliminate
        
        remainder_subst = elem_type(new_R)[]
        for v in current_vars
            if v == var_to_eliminate
                push!(remainder_subst, new_R(0))
            else
                new_idx = findfirst(x -> string(x) == string(v), new_vars)
                push!(remainder_subst, new_vars[new_idx])
            end
        end
        
        remainder_expr_new_R = evaluate(remainder, remainder_subst)
        isolated_rule = -remainder_expr_new_R * inv(c_i)
        
        hom_images = elem_type(new_R)[]
        for v in current_vars
            if v == var_to_eliminate
                push!(hom_images, isolated_rule)
            else
                new_idx = findfirst(x -> string(x) == string(v), new_vars)
                push!(hom_images, new_vars[new_idx])
            end
        end
        
        reduction_map = hom(current_R, new_R, hom_images)
        
        current_M = map_entries(reduction_map, current_M)
        current_f = reduction_map(current_f)
        current_p = deleteat!(copy(current_p), idx_to_eliminate)
        
        current_R = new_R
        current_vars = new_vars
        
        X_k = DeterminantalGerm(current_M, t, current_p)
        glob_idx = global_PHN_index(X_k, current_f, current_p)
        
        # 3. GUARDAR OS ALPHAS SUBSEQUENTES (k = 1, 2, ...)
        push!(alphas, glob_idx)
        
    end
    if print_list
        println("Sequence of Polar Multiplicities: ", alphas)
    end
    return alphas
end

@doc raw"""
    function global_euler_obstruction(M::MatrixElem, t::Int, f::MPolyRingElem, point_P::Vector)
Return the Euler obstruction of a determinantal singularity.
The Euler obstruction is the alternating sum of the global polar multiplicities.

# Example
```jldoctest
julia> R, (x1, x2, x3, x4, x5, x6) = polynomial_ring(QQ, [:x1, :x2, :x3, :x4, :x5, :x6]);

julia> origin = complement_of_point_ideal(R, [0,0,0,0,0,0]);

julia> R_local, _ = localization(R, origin);

julia> t = 2;

julia>  val_1 = QQ(-1//4000000);

julia> M_vars = matrix(R, 2, 3, [x1, x2, x3, x4, x5, x1^2 + x2^2 + x6^2]);

julia> M_pert = matrix(R, 2, 3, [ R(0), R(0), R(0),  R(0),  R(0), val_1]);

julia> M = M_vars + M_pert;

julia> point_P = [QQ(0), QQ(0), QQ(0), QQ(0), QQ(0), 1//2000];

julia> f = 2*x1 + 5*x2 + 3*x3 - 5*x4 - 7*x5 + 11*x6;

julia> global_euler_obstruction(M,2,f,point_P)
-1
```
"""
function global_euler_obstruction(M::MatrixElem, t::Int, f::MPolyRingElem, point_P::Vector)
    # 1. Extrai a lista de multiplicidades polares em silêncio
    alphas = global_polar_multiplicities(M, t, f, point_P; print_list=false)
    
    # 2. Calcula a obstrução de Euler (soma alternada)
    eu_obstruction = 0
    for i in 1:length(alphas)
        eu_obstruction += (-1)^(i - 1) * alphas[i]
    end
    
    return eu_obstruction
end
